% VSIS-Aufgabenblatt
%
% LaTeX-Klasse zur Erstellung von Aufgabenblaettern inkl. optionaler Musterloesung im VSIS-Stil.
%
% Entworfen von Wolfram Wingerath auf Grundlage eines existierenden Designs von Kristof Hamann

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{gdb-aufgabenblatt}[2009/11/08 v1.0 VSIS-Aufgabenblaetter]

\LoadClass{vsis-aufgabenblatt}


\newcommand{\Gruppe}{*Nachnamen der Teilnehmer*}
\newcommand{\STiNEGruppeTitel}{STiNE-Gruppe}
\newcommand{\STiNEGruppe}{01}


\renewcommand{\Vorlesung}{Grundlagen von Datenbanken}
\renewcommand{\Semester}{WS 2014/15}
\renewcommand{\STiNEGruppe}{01}
\renewcommand{\PunktezahlTitel}{\STiNEGruppeTitel~\STiNEGruppe}
\renewcommand{\Punktezahl}{\Gruppe}